/******************************************************************************
 * This file was auto-generated by welds-cli.
 * changes to this file will be overridden when the welds-cli generate command runs again.
 *
 * If you want to take control of this file and prevent welds-cli from overriding it,
 * You can set the flag `manual_update: true` for this table in the welds.yaml config.
******************************************************************************/

use welds::WeldsModel;
#[derive(Debug, WeldsModel)]
#[welds(schema = "public", table = "tb01sys")]
pub struct Tb01Sys {
	#[welds(primary_key)]
	pub key: String,
	pub value: Option<String>,
}
