/******************************************************************************
 * This file was auto-generated by welds-cli.
 * changes to this file will be overridden when the welds-cli generate command runs again.
 *
 * If you want to take control of this file and prevent welds-cli from overriding it,
 * You can set the flag `manual_update: true` for this table in the welds.yaml config.
******************************************************************************/

use welds::WeldsModel;

use crate::db::db::{DATETIME, TIMESTAMP};
#[derive(Debug, WeldsModel)]
#[welds(schema = "dbo", table = "sysUser")]
pub struct SysUser {
	#[welds(primary_key)]
	#[welds(rename = "UserCode")]
	pub user_code: String,
	#[welds(rename = "Accessid")]
	pub accessid: Option<String>,
	pub changepwd: Option<bool>,
	pub channel: Option<String>,
	pub classid: Option<String>,
	pub classname: Option<String>,
	#[welds(rename = "Companyid")]
	pub companyid: String,
	pub dataday: Option<i32>,
	pub daytype: Option<String>,
	#[welds(rename = "DepartmentId")]
	pub department_id: Option<String>,
	#[welds(rename = "DepartmentName")]
	pub department_name: Option<String>,
	pub description: Option<String>,
	#[welds(rename = "DOCOPID")]
	pub docopid: Option<String>,
	pub hrcode: Option<String>,
	pub is_change: Option<bool>,
	pub is_manager: Option<i32>,
	pub is_manu: Option<bool>,
	#[welds(rename = "isMgr")]
	pub is_mgr: Option<bool>,
	pub ismodifyflag: Option<i32>,
	#[welds(rename = "JxCode")]
	pub jx_code: Option<i32>,
	#[welds(rename = "JxGroupid")]
	pub jx_groupid: Option<String>,
	pub memo: Option<String>,
	#[welds(rename = "memo1")]
	pub memo_1: Option<String>,
	pub modifydate: Option<DATETIME>,
	pub modifyname: Option<String>,
	pub msghrcode: Option<String>,
	pub need_stop: Option<bool>,
	pub oldpassword: Option<String>,
	pub parentrowid: Option<String>,
	#[welds(rename = "PassWord")]
	pub pass_word: Option<String>,
	#[welds(rename = "password2")]
	pub password_2: Option<String>,
	pub peridodclolsed: Option<String>,
	pub positionid: Option<String>,
	pub positionname: Option<String>,
	#[welds(rename = "ProfileID")]
	pub profile_id: Option<String>,
	pub rowid: Option<String>,
	pub shortno: Option<String>,
	pub stamp: Option<TIMESTAMP>,
	#[welds(rename = "Stop_Flage")]
	pub stop_flage: Option<i32>,
	pub stoped: Option<bool>,
	pub telserverip: Option<String>,
	pub uniqid: i32,
	#[welds(rename = "UserName")]
	pub user_name: Option<String>,
	pub wagepass: Option<String>,
	pub wkhrcode: Option<String>,
	#[welds(rename = "Wxuserid")]
	pub wxuserid: Option<String>,
}
