services:
  webserver:
    stdin_open: true
    image: mm.io/${APP_ID:-mm}-web:dev
    environment:
      - APP_ID=${APP_ID:-mm}
    volumes:
      - ~/data:/data
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - ~/.vscode/tasks:/tasks
      - ~/exts:/exts
      - ../:/host
      - ~/.cache:/usr/local/share/.cache
    build:
      context: ..
      dockerfile: .devcontainer/app
