services:
  webserver:
    stdin_open: true
    image: mm.io/${APP_ID:-mm}-web:dev
    environment:
      - APP_ID=${APP_ID:-mm}
    volumes:
      - ~/data:/data
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - ~/.vscode/tasks:/tasks
      - ~/exts:/exts
      - ../:/host
      - ~/.cache:/usr/local/share/.cache
    build:
      context: ..
      dockerfile: .devcontainer/app

  db:
    image: docker.cnb.cool/mmstudio666/images/postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME:-mm}
      - POSTGRES_USER=${DB_USER:-mm}
      - POSTGRES_PASSWORD=${DB_PSWD:-mm}
    volumes:
      - ../init.d/mm.sql:/docker-entrypoint-initdb.d/mm.sql

  nginx:
    image: docker.cnb.cool/mmstudio666/images/nginx:latest
    environment:
      - NGINX_PORT=${NGINX_PORT:-3456}
      # - NGINX_BASEPATH=${NGINX_BASEPATH:-mm}
      - NGINX_DOMAIN=${NGINX_DOMAIN:-localhost}
      - TZ=Asia/Shanghai
    ports:
      - ${NGINX_PORT:-3456}:${NGINX_PORT:-3456}
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template

  doccode:
    image: docker.cnb.cool/mmstudio666/images/doccode:latest
    environment:
      - DOCCODE_TB=${DOCCODE_TB:-tb01doccode}
      - DOCCODE_PORT=${DOCCODE_PORT:-8090}
      - DOCCODE_DBNAME=${DB_NAME:-mm}
      - DOCCODE_DBUSR=${DB_USER:-mm}
      - DOCCODE_DBPSW=${DB_PSWD:-mm}
      - DOCCODE_DBHOST=${DOCCODE_DBHOST:-db}
      - DOCCODE_DBPORT=${DOCCODE_DBPORT:-5432}

  adminer:
    image: docker.cnb.cool/mmstudio666/images/adminer:latest

  minio:
    image: docker.cnb.cool/mmstudio666/images/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_USER:-mmstudio}
      - MINIO_ROOT_PASSWORD=${MINIO_PSWD:-mmstudio}

  fileview:
    image: docker.cnb.cool/mmstudio666/images/fileview:latest
